### ISSUE TITLE
[Future Request] New function too reload the phrase files 

### ISSUE THREAD

**Issue by fawazorg** [dawalters1/wolf.js#139]
Hi @dawalters1 

Thank you for all you hard work and this awesome library "Wolf.js" it's make our unofficial bot doing great.

So allow me to ask you if there any chance to add a new function to phrase helper file called reload so we can update the phrase file's without restart the bot.

basics of function Reload : 
// clear the _phrase
clear();
// call _local_load
_local_load();

Again thank you and look forward to v2 . Can't wait .

**Comment by dawalters1** [comment]
https://github.com/dawalters1/wolf.js/blob/version2/src/helper/phrase/Phrase.js#L19

**Comment by fawazorg** [comment]
i ask if you can do it on this version as well
