### ISSUE TITLE
[Phrase] function getByCommandAndName should be accepte Command type not CommandContext

### ISSUE THREAD

**Issue by fawazorg** [dawalters1/wolf.js#158]
Hi 

I think this function should be accepte type of command not CommandContext because when you make a new command you pass command in the me function (in readme.md) example that is not CommandContext you pass it's command type.

https://github.com/dawalters1/wolf.js/blob/9cc8dedd6f0b2e3816f7b5120ce064ed5273a7b7/src/helper/phrase/Phrase.js#L122-L132

**Comment by fawazorg** [comment]
command prams here it's Command type not CommandContext
https://github.com/dawalters1/wolf.js/blob/9cc8dedd6f0b2e3816f7b5120ce064ed5273a7b7/README.md?plain=1#L158-L179

**Comment by dawalters1** [comment]
In WJS 2 Command is referred to as Command Context in this case
