### ISSUE TITLE
VIP privilege is undefined in constants privileges

### ISSUE THREAD

**Issue by fawazorg** [dawalters1/wolf.js#175]
Hi Dew. 

I hop every thing is okay with you. 

In wolf.js index.d.ts VIP privilege it is in enum Privileges, but it's not in constants, so it's error out if you try it.

In privilage.js
```js
export const VIP = 2097152; 
```

**Comment by fawazorg** [comment]
```js
export const VIP = 1 << 21;

**Comment by dawalters1** [comment]
2.2.1
