### ISSUE TITLE
[Notifications Helper] some functions not accept parameters as index.d.ts

### ISSUE THREAD

**Issue by fawazorg** [dawalters1/wolf.js#176]
In index.d.js notifications.subscriber.list say its accept limit and offset as parameters but the function its self don't do that

https://github.com/dawalters1/wolf.js/blob/474fef3b9918fbaf4f95d08e90227ecfad429354/typings/index.d.ts#L1110-L1118

https://github.com/dawalters1/wolf.js/blob/474fef3b9918fbaf4f95d08e90227ecfad429354/src/helper/notification/Subscriber.js#L104-L114

**Comment by fawazorg** [comment]
In index.d.js notifications.subscriber.list say its accept limit and offset as parameters but the function its self don't do that

https://github.com/dawalters1/wolf.js/blob/474fef3b9918fbaf4f95d08e90227ecfad429354/typings/index.d.ts#L1110-L1118

https://github.com/dawalters1/wolf.js/blob/474fef3b9918fbaf4f95d08e90227ecfad429354/src/helper/notification/Subscriber.js#L104-L114

**Comment by fawazorg** [comment]
The same with delete function

https://github.com/dawalters1/wolf.js/blob/474fef3b9918fbaf4f95d08e90227ecfad429354/typings/index.d.ts#L1125-L1132

https://github.com/dawalters1/wolf.js/blob/474fef3b9918fbaf4f95d08e90227ecfad429354/src/helper/notification/Subscriber.js#L151-L160

**Comment by fawazorg** [comment]
In global notification as well as above comments, same functions

**Comment by dawalters1** [comment]
2.2.1
