### ISSUE TITLE
[Stage Helper] Update GroupAudioSlotRequest to ChannelAudioSlotRequest

### ISSUE THREAD

**Issue by fawazorg** [dawalters1/wolf.js#177]
https://github.com/dawalters1/wolf.js/blob/474fef3b9918fbaf4f95d08e90227ecfad429354/src/helper/stage/Request.js#L38-L41

**Comment by fawazorg** [comment]
This Model as well : GroupAudioSlot
https://github.com/dawalters1/wolf.js/blob/474fef3b9918fbaf4f95d08e90227ecfad429354/src/helper/stage/Slot.js#L37-L42

**Comment by dawalters1** [comment]
2.2.1
