### ISSUE TITLE
[Store Helper] typo in 'quanitity' parameter effect purchase function to work

### ISSUE THREAD

**Issue by fawazorg** [dawalters1/wolf.js#178]
There is typo in quantity parameter: 

I double-check with the server it's quantity not quanitity

The effect in emit event :

https://github.com/dawalters1/wolf.js/blob/474fef3b9918fbaf4f95d08e90227ecfad429354/src/helper/store/Store.js#L207-L257

**Comment by dawalters1** [comment]
2.2.1
