### ISSUE TITLE
Set volume error

### ISSUE THREAD

**Issue by idevelopr** [dawalters1/wolf.js#183]
{"level":1,"message":"TypeError: volume.toPrecision is not a function\n    at Client.setVolume

**Comment by dawalters1** [comment]
Is this still an issue on 2.2.1?

**Comment by fawazorg** [comment]
@dawalters1 The stage client doesn't need the wolf client, it's overridden here [35,42]

https://github.com/dawalters1/wolf.js/blob/fabf750537dca589ebb6d612701b54dcdb65888e/src/client/stage/Client.js#L27-L44

**Comment by dawalters1** [comment]
Closing.
