### ISSUE TITLE
Unnecessary Error Message in Some Cases

### ISSUE THREAD

**Issue by burakgarci** [dawalters1/wolf.js#272]
This error is being thrown away in some cases where the image does not have to be square, as in uploading a thumbnail for a channel event. Perhaps a better approach might be considered for different cases or throw and error depending on the server response.

https://github.com/dawalters1/wolf.js/blob/0148d94549da0c37143faf43d0c73eb881ae7b8e/src/utils/validateMultimediaConfig.js#L16

**Comment by dawalters1** [comment]
the framework config has a toggle for as I had this in mind, however pretty sure last time I checked thumbnails were required to be square.

**Comment by dawalters1** [comment]
npm i wolf.js@2.4.4
