### ISSUE TITLE
member.kick() Sends Incorrect Command and Missing Parameter

### ISSUE THREAD

**Issue by burakgarci** [dawalters1/wolf.js#353]
`client.channel.member.kick(channelId, subscriberId)` causes the bot to leave the target channel because the command sent to the server is wrong and also the kick action is missing as the 3rd parameter. 

https://github.com/dawalters1/wolf.js/blob/97a904ea50c83e4881118bea3ed41fb2e9c5c6df/src/helper/channel/Member.js#L661

Correct use should be as follows?: 
``` js
return await this.client.websocket.emit(
  Command.GROUP_MEMBER_UPDATE,
  {
    groupId: parseInt(targetChannelId),
    id: parseInt(subscriberId),
    capabilities: AdminAction.KICK
  }
);

**Comment by dawalters1** [comment]
GROUP_MEMBER_DELETE is correct, however the body was incorrect
