### ISSUE TITLE
Download & Number utility should not expect api on constructor.

### ISSUE THREAD

**Issue by fawazorg** [dawalters1/wolf.js#88]
_api parameter never used :

https://github.com/dawalters1/wolf.js/blob/b4e83736caef8432e149f683511adab9c66d2de2/src/utils/Download/index.js#L4-L7

https://github.com/dawalters1/wolf.js/blob/b4e83736caef8432e149f683511adab9c66d2de2/src/utils/Number/index.js#L1-L4

**Comment by dawalters1** [comment]
Yea unsure why I did this, I probably had other stuff in mind and just never did it, that or I copy and pasted the constructor

**Comment by dawalters1** [comment]
Removed in beta 17
